let num = 100;
let fname = "manan";
let result = true;
let id;
let fullname;
let msg = "manan shah";
msg = 200;
msg = true;
console.log("value of num is " + num);
console.log("value of fname is " + fname);
console.log("value of result is " + result);
console.log("value of id is " + id);
console.log("value of fullname is " + fullname);
console.log("value of msg is " + msg);
